version: "3"
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: leandromatospereira/nginx
    container_name: nginx
    ports: 
      - "80:80"
    networks: 
      - prod-network
    depends_on:
      - "node1"
      - "node2"
      - "node3"
  
  mongodb:
    image: mongo
    networks:
      - prod-network
  
  node1:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: leandromatospereira/node-book
    container_name: node-book-1
    ports:
      - "3000"
    networks:
      - prod-network
    depends_on:
      - "mongodb"

  node2:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: leandromatospereira/node-book
    container_name: node-book-2
    ports:
      - "3000"
    networks:
      - prod-network
    depends_on:
      - "mongodb"

  node3:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: leandromatospereira/node-book
    container_name: node-book-3
    ports:
      - "3000"
    networks:
      - prod-network  
    depends_on:
      - "mongodb"

networks:
  prod-network:
    driver: bridge